name: "templ-generator-action"
description: "An action that generates Go code from templ files"
inputs:
  directory:
    description: "The directory where to look for .templ files."
    required: false
    default: "."
  commit:
    description: "Flag to enable or disable committing changes."
    required: false
    default: "true"
  commit-message:
    description: "Custom commit message for the generated code."
    required: false
    default: "chore: Generate templ code"
  format:
    description: "Flag to enable or disable formatting the generated code."
    required: false
    default: "true"
  setup-go:
    description: "Flag to enable or disable setting up Go."
    required: false
    default: "true"
  go-version:
    description: "The Go version to use."
    required: false
    default: "stable"
  templ-version:
    description: "The templ version to use."
    required: false
    default: "latest"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@v5
      if: ${{ inputs.setup-go == 'true' }}
      with:
        go-version: ${{ inputs.go-version }}
    - name: Install templ
      shell: bash
      run: go install github.com/a-h/templ/cmd/templ@${{ inputs.templ-version }}
    - name: Run templ fmt
      if: ${{ inputs.format == 'true' }}
      shell: bash
      run: templ fmt ${{ inputs.directory }}
    - name: Run templ generate
      shell: bash
      run: templ generate -path ${{ inputs.directory }}
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v5
      if: ${{ inputs.commit == 'true' }}
      with:
        commit_message: ${{ inputs.commit-message }}
branding:
  icon: "layout"
  color: "gray-dark"
